###
POST http://localhost:5000/api/v1/people/person HTTP/1.1
Content-Type: application/json

{
  "name":"Sofia",
  "lastname":"Piñuela",
  "dni":"1054398",
  "address":[{
    "city":"Manizales",
    "code_zip":170002,
    "geo":[-6.125152,8.23923]
  }]
}
###
GET http://localhost:5000/api/v1/people HTTP/1.1
###
GET http://localhost:5000/api/v1/people/623b73ced1a7fc20ef4bd377 HTTP/1.1
###
PUT http://localhost:5000/api/v1/people/623b73ced1a7fc20ef4bd377 HTTP/1.1
Content-Type: application/json

{
  "address":[{
    "city":"Bogota",
    "code_zip":170001,
    "geo":[-6.125152,8.23923]
  }]
}
###
DELETE http://localhost:5000/api/v1/people/623b6e7d0deb2b011d20812b HTTP/1.1

//V1

###
POST http://localhost:5000/api/v1/superheroes/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero":"Spiderman red",
  "real_name":"peter parker",
  "feature":[{
    "universe":"universe",
    "super_powers":["arañas","volar"]
  }],
   "superhero_sidekick":[{
    "sidekick":"universe",
    "side_powers":["volar","invisibilidad                                                                                                                                                                                           "]
  }]

}
###
GET http://localhost:5000/api/v1/superheroes HTTP/1.1

###
GET http://localhost:5000/api/v1/superheroes/623d296f28a2c9f86082b53f HTTP/1.1

###
PUT http://localhost:5000/api/v1/superheroes/623d296f28a2c9f86082b53f HTTP/1.1
Content-Type: application/json

{
 "superhero":"Spiderman2",
  "real_name":"peter"
}
###
DELETE http://localhost:5000/api/v1/superheroes/623d296f28a2c9f86082b53f HTTP/1.1

//V2

###
POST http://localhost:5000/api/v1/superheroes_v2/superhero HTTP/1.1
Content-Type: application/json

{
  "superhero":"Wolverine",
  "realname":"Wol",
  "superpower":"Be "
}
###
GET http://localhost:5000/api/v1/superheroes_v2 HTTP/1.1

###
GET http://localhost:5000/api/v1/superheroes_v2/623b2454de46bc4fd18d3203 HTTP/1.1

###
PUT http://localhost:5000/api/v1/superheroes_v2/623b284ecbfb9c0a2181972f HTTP/1.1
Content-Type: application/json
{
  "superhero":"Batman Bru"
}
###
DELETE http://localhost:5000/api/v1/superheroes_v2/623b284ecbfb9c0a2181972f HTTP/1.1



